### ISSUE TITLE
Quarks install won't work as in the README

### ISSUE THREAD

**Issue by gilfuser** [madskjeldgaard/plugins.quark#1]
Hi!

This won't work:
`Quarks.install("https://github.com/madskjeldgaard/plugins.quark.git")`
it will install a `plugins.quark` folder

but this will:
`Quarks.install("https://github.com/madskjeldgaard/plugins.quark")`
will install a `plugins` folder

**Comment by madskjeldgaard** [comment]
Thanks!! I fixed it now
